apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: pod1-container
      image: nginx:latest
      ports:
        - containerPort: 80
  